export class Parceiro {
  constructor(
    public id?: number,
    public cnpj?: string,
    public nome_fantasia?: string,
    public razao_social?: string,
    public telefone?: string,
    public cep?: string,
    public logradouro?: string,
    public numero?: string,
    public complemento?: string,
    public bairro?: string,
    public cidade?: string,
    public estado?: string,
    public email_parceiro?: string,
    public midia_social?: string,
    public instagram_parceiro?: string,
    public tipo_service?: string,
    public tipo_estabelecimento?: string,
    public tipo_estabelecimento_outros?: string,
    public essential_service?: string,
    public internet_speed?: string,
    public internet_service?: string,
    public outro_servico?: string,
    public trabalho_reunioes?: string,
    public tarifa_especial?: string,
    public internet_service_alimentacao?: string,
    public orienta_equipe?: string,
    public localizacao?: string,
    public ramo?: string,
    public beneficios?: string,
    public espacos_culturais?: string,
    public idioma?: string,
    public qual_idioma?: string,
  ){}
}
